Facebook login
Huascar-Ona/perritos pull request #1
Opened 2017-02-11 06:56 UTC by jizavala

- Modifica el gemfile para incluir las gemas devise, onmiauth-facebook, wdm y certified. 
- Agregado el controllador para el callback del onmiauth. 
- Modificado el routes para implementar los controllers del onmiauth. 
- Agregado el modelo Users. 
- Agregada la vista de la pagina que contendra el login mediante facebook y su respectivo logout.

2017-02-15 16:07 UTC, escoberik requested changes
El código se ve bien en general. Pequeñas correcciones. En cuanto a los assets JS, usamos otra herramienta para manejarlos. Por el momento está bien como lo estás haciendo. En un futuro cercano migramos a la herramienta. Se llama `bower`,  por si tienes tiempo de darle una checada

2017-02-15 16:07 UTC, erik-escobedo commented on Gemfile
> +gem 'wdm'
Esta gema agrégala solo en `group: :development`

2017-02-15 16:07 UTC, erik-escobedo commented on Gemfile
> +gem 'certified'
Buena. Esta no me la sabía 👍

2017-02-15 16:07 UTC, erik-escobedo commented on Gemfile
> +gem 'certified'
Pero ahora que lo pienso, también va en `group: :development`

2017-02-15 16:07 UTC, erik-escobedo commented on Gemfile
> +
Y esto para qué es? o.O

2017-04-21 20:59 UTC, jizavala commented on Gemfile
> +gem 'certified'
Agregada gem certified al group development.

2017-04-21 21:00 UTC, jizavala commented on Gemfile
> +gem 'wdm'
Agregada gem wdm al group development.

2017-04-21 21:00 UTC, jizavala commented on Gemfile
> +
Se removio esta gema ya que tiene un uso similar al rake.

2017-06-07 19:36 UTC, closed without merging